services:
  www:
    build:
      dockerfile: ./dockerfile.www
    volumes:
      - "./dice_models:/app/dice_models"
      - "./db:/app/db"
      - "./docker/www/prestart.sh:/app/prestart.sh"
    ports:
      - "80:80"
    environment:
      IS_DEV: true
      RELOAD: true
