ARG PYTHON_VERSION=3.13
FROM ghcr.io/multi-py/python-uvicorn:py${PYTHON_VERSION}-slim-LATEST

ENV APP_MODULE=dice_models.www:app

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY ./docker/www/prestart.sh /app/prestart.sh
COPY ./ /app
